# Generated by Django 4.1 on 2022-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='segundo_apellido',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='segundo_nombre',
            new_name='celular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='barrio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='enfermedades',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eps',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='medicamentos',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rh',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
