# Generated by Django 4.1 on 2022-10-31 02:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0002_rename_segundo_apellido_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.CharField(max_length=40, null=True)),
                ('Departamento', models.IntegerField(choices=[[0, 'oftalmologia'], [1, 'Dermatologia'], [2, 'Patologia'], [3, 'Consulta'], [4, 'Operaciones'], [5, 'Odontologia']])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
