# Generated by Django 4.1 on 2022-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_doctores'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctores',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
