# Generated by Django 4.1 on 2022-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha1', models.DateField()),
                ('fecha2', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('Departamento', models.IntegerField(choices=[[0, 'oftalmologia'], [1, 'Dermatologia'], [2, 'Patologia'], [3, 'Consulta'], [4, 'Operaciones'], [5, 'Odontologia']])),
                ('celular', models.CharField(max_length=40, null=True)),
                ('Doctor', models.CharField(max_length=50)),
            ],
        ),
    ]
